### ISSUE TITLE
unable to start td-agent

### ISSUE THREAD

**Issue by calljsaran** [treasure-data/fluent-plugin-td#33]
I am using Mac os and installed td-agent using the following link
https://docs.fluentd.org/installation/install-by-dmg and then run the following commands to launch the td-agent

To run :
sudo launchctl load /Library/LaunchDaemons/td-agent.plist

I modifed the the conf file which is placed in /opt/td-agent/etc/td-agent
<source>
@type tail
  path /Users/calljsaran/Desktop/elk-logs/saran-json.json
  pos_file /Users/calljsaran/Desktop/elk-logs/saran-json.json.pos
  format json
  time_format %Y-%m-%dT%H:%M:%S
  tag saran-json
</source>

<match *saran-json*>
 @type elasticsearch
 host http://localhost:9200
 index_name omnistore
 type_name log
</match>

and launched td-agent using :

sudo launchctl load /Library/LaunchDaemons/td-agent.plist

When I check the logs I can see my td-agent.conf file is not parsed and it is still using some files in the root

_2020-04-30 19:33:04 +0530 [info]: parsing config file is succeeded path="/etc/td-agent/td-agent.conf"

2020-04-30 19:33:05 +0530 [warn]: [output_td] secondary type should be same with primary one primary="Fluent::Plugin::TreasureDataLogOutput" secondary="Fluent::Plugin::FileOutput"

2020-04-30 19:33:05 +0530 [info]: using configuration file: <ROOT>

  <match td.*.*>

    @type tdlog

    @id output_td

    apikey xxxxxx

    auto_create_table 

    <buffer>

      @type "file"

      path "/var/log/td-agent/buffer/td"

    </buffer>

    <secondary>

      @type "file"

      path "/var/log/td-agent/failed_records"

      <buffer time>

        path /var/log/td-agent/failed_records

      </buffer>

    </secondary>

  </match>

  <match debug.**>

    @type stdout

    @id output_stdout

  </match>

  <source>

    @type forward

    @id input_forward

  </source>

  <source>

    @type http

    @id input_http

    port 8888

  </source>

  <source>_

It seems my conf file was not used. Where is the issue ?Can you pls help me in solving this?

**Comment by repeatedly** [comment]
Multi post and bad location for the question.
